name: Fifa
favicon: null
layout_spectrum: 0.55424
typography_spectrum: 0.51606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#f1e4d3'
    - '#798255'
    - '#6d3d31'
    - '#156e1a'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
